"""Add due_date and repeat_interval to Task model

Revision ID: 697135a82a6e
Revises: ce27fd554996
Create Date: 2025-12-09 07:33:47.433534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697135a82a6e'
down_revision: Union[str, None] = 'ce27fd554996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    # Create the ENUM type before using it in the column
    op.execute("CREATE TYPE repeatinterval AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY')")
    op.add_column('task', sa.Column('repeat_interval', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='repeatinterval'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'repeat_interval')
    # Drop the ENUM type after dropping the column
    op.execute("DROP TYPE repeatinterval")
    op.drop_column('task', 'due_date')
    # ### end Alembic commands ###