"""Add priority and tags as string to Task model

Revision ID: ce27fd554996
Revises: b6dac14d5567
Create Date: 2025-12-09 07:26:01.782195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ce27fd554996'
down_revision: Union[str, None] = 'b6dac14d5567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcements')
    op.drop_table('members')
    op.drop_table('metadata')
    op.drop_table('rules_and_regulations')
    
    # Create the ENUM type before using it in the column
    op.execute("CREATE TYPE priority AS ENUM ('LOW', 'MEDIUM', 'HIGH')")
    op.add_column('task', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority'), nullable=True))
    op.add_column('task', sa.Column('tags', sa.String(), nullable=True)) # Use sa.String() for plain string
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'tags')
    op.drop_column('task', 'priority')
    # Drop the ENUM type after dropping the column
    op.execute("DROP TYPE priority")

    op.create_table('rules_and_regulations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rules_and_regulations_pkey'))
    )
    op.create_table('metadata',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('metadata_pkey'))
    )
    op.create_table('members',
    sa.Column('member_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.TEXT(), server_default=sa.text("'Unpaid'::text"), autoincrement=False, nullable=False),
    sa.Column('amount', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'User'::text"), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password_salt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("payment_status = ANY (ARRAY['Paid'::text, 'Unpaid'::text])", name=op.f('members_payment_status_check')),
    sa.CheckConstraint("role = ANY (ARRAY['Admin'::text, 'User'::text])", name=op.f('members_role_check')),
    sa.PrimaryKeyConstraint('member_id', name=op.f('members_pkey'))
    )
    op.create_table('announcements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('announcements_pkey'))
    )
    # ### end Alembic commands ###